cloudfoundry-incubator/eirini

- bifrost/bifrost.go
- bifrost/bifrost_test.go
- bifrost/convert.go
- bifrost/convert_test.go
- bifrost/models.go
- k8s/deployment.go
- k8s/deployment_test.go
- k8s/desire.go
- k8s/desire_test.go
- k8s/ingress.go
- k8s/ingress_test.go
- k8s/k8sfakes/fake_ingress_manager.go
- models.go
- models/cf/models.go
- opi/model.go
In order to have easier access to required VCAP_APPLICATION data, this
commit introduces Metadata which saves all necessary information in a
map. This includes - beside the vcap info - the process_guid which is
comming from desiredLRPRequestFromCC.
Signed-off-by: Julian Skupnjak <skupnjak@de.ibm.com>
Signed-off-by: Georgi Dankov <gddankov@gmail.com>
Signed-off-by: Steffen Uhlig <Steffen.Uhlig@de.ibm.com>
> Introduce Metadata field and provide process_guid to kube deployments.

- cmd/opi/cmd/connect.go
- k8s/ingress.go
- k8s/ingress_test.go
- route/collector.go
- route/collector_test.go
The ingress rule needs to be created such that the host name matches the app route (if multiple app routes, you need multiple ingress rules). When registering a route, it is important to set the host to the kubernetes/ingress endpoint only.
> Refactor creation and registration of routes

- .golangci.yml
All failing linters are disabled. This will make the pipeline initially green. Future chores will make this list empty.
> Add static code checks configuration

- k8s/deployment.go
- k8s/deployment_test.go
- k8s/desire_test.go
Currently when an app is stopped, the deployment and service for that app are deleted, but the replicaset (and therefore pods) associated with the deployment are not. 
This PR should fix this.
> Fix pod leaking on app stop

- k8s/k8sfakes/fake_service_manager.go
- k8s/service.go
- k8s/service_test.go
- k8s/statefulset.go
- k8s/statefulset_test.go
* Add a `DeleteHeadless` method in `ServiceManager`
* Use it when deleting a `StatefulSet`
[#159335321]
> Delete the associated Headless Service when deleting a StatefulSet

- bifrost/convert.go
- bifrost/convert_test.go
Guys, we need to make another minor adjustment to how we identify OCI images. The way Cloud Controller (and therefore Bits-Service) stores droplets is:
```
/cc-droplets/so/me/some-droplet-guid/the-droplet-hash
```
So this change adjusts this and makes both things available to us.
/cc @JulzDiverse @suhlig
> Use droplet GUID and droplet Hash to identify OCI images

- bifrost/bifrost_test.go
This is a tricksy race condition that occurs because the tests are currently not run in parallel by `ginkgo` in the eirini CI/contributor script. It also outlines that one of the tests wasn't testing expected behaviour at all.
If the tests are run in parallel the tests fail with things like:
```
-----------------------------
•! Panic [0.001 seconds]
Bifrost
/home/vagrant/go/src/code.cloudfoundry.org/eirini/bifrost/bifrost_test.go:21
List
/home/vagrant/go/src/code.cloudfoundry.org/eirini/bifrost/bifrost_test.go:108
When listing running LRPs
/home/vagrant/go/src/code.cloudfoundry.org/eirini/bifrost/bifrost_test.go:137
should translate []LRPs to []DesiredLRPSchedulingInfo [Measurement]
/home/vagrant/go/src/code.cloudfoundry.org/eirini/bifrost/bifrost_test.go:151
Test Panicked
runtime error: …
```
> Fix race in bifrost List tests

- cmd/opi/cmd/connect.go
- route/emitter.go
- route/emitter_test.go
The route emitter structure has a few `fmt.Println`s sprinkled around. This is not ideal for a couple of reasons:
1. When unit testing, _expected_ error messages get printed out to the test `stdout`, which is confusing when all the tests are actually passing.
2. Having some library depths print to stdio streams is pretty annoying, there's no way to turn it off.
This PR introduces a log to the `Emitter` struct that can be injected. In tests we then multiwriter to a buffer we can assert on (turns out, these error logs were not actually being tested), and to the GinkgoWriter, so if a test fails we still get the output.
A few further notes on this:
- Errors probably shouldn't be going to `stdout` at all, but I didn't change it to `stderr` because that would be a behavioural change.
- It's …
> Stop the route emitter logging directly to stdout

- cmd/opi/cmd/connect.go
- models.go
This PR adds support for the `opi` binary to run outside of the Kubernetes cluster where CF workloads are being scheduled.
Specifically, this PR adds a configurable property to specify a kube config file (`kube_config_path`). If the `kube_config_path` property in the config file does not exist or is empty, then there is no behavior change.
This is a potential solution to issue #51.
There don't seem to be existing unit tests at this level. We can add a new test file here if you want.
Thanks!
Jen & @jspawar
> Enable Eirini to run outside of a k8s cluster

- bifrost/bifrost.go
- cmd/opi/cmd/connect.go
- handler/app_handler.go
- integration/rootfs_patcher_test.go
- integration/statefulset_test.go
- k8s/informers/event/crash.go
- k8s/informers/event/crash_test.go
- k8s/statefulset.go
- k8s/statefulset_test.go
- route/emitter.go
- route/emitter_test.go
We've found it helpful to have some more logging in error cases, so we've added a few log lines to various parts of eirini.
We've also converted a few places that used `Printf` or the Golang built-in logging library to use `lager.Logger` instead for consistency (and so that lager-log-processing tools like `veritas` work well).
We updated tests to reflect these changes. We also needed to pass in a test logger in a couple places where we've updated the function signature to expect a logger.
Thanks!
Jen + @jspawar
> Add more logs for errors cases

- cmd/opi/cmd/connect.go
Instead of prefixing log messages with UNIX Epoch time, which is hard for humans to understand at a glance, use a human readable timestamp format that is also computer-friendly (RFC 3339)
So instead of seeing: 
> { "source": "my-app", "message": "doing-stuff", "data": { "informative": true }, "timestamp": 1556306603, "log_level": 1 }
You should now see:
> { "source": "my-app", "message": "doing-stuff", "data": { "informative": true }, "timestamp": 2019-04-26T19:23:23+00:00, "log_level": 1 }
Thanks,
Jwal + @jenspinney
> Use human-readable timestamps in log messages

- stager/stager.go
- stager/stager_test.go
Keeping the failed job allows for later inspection of failed staging to see the failure reason and debug.
[#166678515](https://www.pivotaltracker.com/story/show/166678515)
> keep the staging job when it fails

- k8s/informers/route/instance_informer_test.go
- k8s/informers/route/uri_informer.go
- k8s/informers/route/uri_informer_test.go
- k8s/route_collector.go
- k8s/route_collector_test.go
Added a fix so that `RTR` messages appear in the output of `cf logs` for this story in the Eirini backlog: https://www.pivotaltracker.com/story/show/165745052
Had to modify the NATS messages to the gorouter to advertise the app by its GUID instead of the pod's name.
Thanks,
Jwal + @madamkiwi
> Allow RTR messages to appear in cf logs stream

- k8s/informers/event/crash_report_generator.go
- k8s/informers/event/crash_report_generator_test.go
- k8s/utils/pod_state.go
- k8s/utils/pod_state_test.go
Progress towards #79
We changed the way we determine whether the pod is crashed or running by checking the status of **all containers** on the pod, not only the first one. This required when we inject sidecars into pods.
[#169685576](https://www.pivotaltracker.com/story/show/169685576)
cc @rosenhouse @tcdowney
> Support multicontainer pods for status and crash reports

- integration/cmd/connect_test.go
- integration/opi/opi_suite_test.go
The following has been tested against a local KinD kubernetes cluster.
When run locally the connect and opi-suite tests were producing timeouts, so I increased the time limits. This is purely a change to enable local development.
> Increase integration tests timeout limit

- integration/statefulset_test.go
- integration/statefulsets_suite_test.go
- k8s/statefulset.go
- k8s/statefulset_test.go
This is achieved by creating inter-pod anti-affinity for each app.
[#170993583]
> Schedule app pods on different nodes when possible

- k8s/mapper.go
- k8s/mapper_test.go
* we believe this fixes some bugs we've found when trying to get v3 deployments working.
* it generally seems more correct to keep this guid consistent and not entangle it with other CF concepts. 
* these issues appear when a process's guid != its app guid, like after a v3 deployment. prior to rolling deployments, an app's web process and the app itself will always have the same guid. 
[fixes https://www.pivotaltracker.com/story/show/168391143]
Co-authored-by: Connor Braa <cbraa@pivotal.io>
Co-authored-by: Seth Boyles <sboyles@pivotal.io>
> use lrp guid instead of app guid when translating statefulsets

- docker/bits-waiter/Dockerfile
- docker/event-reporter/Dockerfile
- docker/metrics-collector/Dockerfile
- docker/opi/Dockerfile
- docker/rootfs-patcher/Dockerfile
- docker/route-collector/Dockerfile
- docker/route-pod-informer/Dockerfile
- docker/route-statefulset-informer/Dockerfile
- docker/staging-reporter/Dockerfile
This PR will allow the building of the images on a different base. For example, we need to build all the images with a SLE (SUSE Linux Enterprise) base for kubecf.
Relevant kubecf issue: https://github.com/cloudfoundry-incubator/kubecf/issues/744
This image was skipped: https://github.com/cloudfoundry-incubator/eirini/blob/master/docker/registry/certs/smuggler/Dockerfile
because the `FROM` line is not enough to change to another distro (there are `apk` commands in the Dockerfile) and we won't need this image in kubecf.
> Parameterize baseimage in Dockerfiles

- cmd/opi/cmd/connect.go
- integration/cmd/connect_test.go
- models.go
Adds a property `serve_plaintext` which is false by default. If it's explicitly set to `true` OPI will serve plaintext instead of TLS. It also adds a `plaintext_port` property to set the plaintext port.
fixes #95
> Serve plaintext if `serve_plaintext` is true

- models.go
Thanks for contributing to Eirini! In order for your pull request to be accepted, we would like to ask you the following:
1. Please base your PR off the `master` branch.
Forked on master.
1. Describe the change on a conceptual level. How does it work, and why should it exist? Ideally, you contribute a few words to the README, too.
Unfortunately, it looks like a typo made it into the custom key for yaml unmarshalling for `MetricsCollectorConfig`. The key is inconsistent with other loggregator keys.
1. Please provide automated tests (preferred) or instructions for manually testing your change.
Test coverage does not currently extend to unmarshalling out of json; test fixtures provide data directly. I can add test coverage if it is desired.
> Fix custom key spelling for LoggregatorCertPath

- docker/instance-index-env-injector/Dockerfile
To allow people to build it on a different base image
Thanks for contributing to Eirini! In order for your pull request to be accepted, we would like to ask you the following:
> Make instance index env injector image configurable through build args

- k8s/desiretask.go
- k8s/desiretask_test.go
- k8s/helpers.go
- k8s/statefulset.go
- k8s/statefulset_test.go
- tests/assets/docker/Makefile
- tests/assets/docker/busybox/Dockerfile
- tests/assets/docker/icarus/Dockerfile
- tests/eats/events_crd_test.go
- tests/eats/task_reporter_test.go
- tests/eats/tasks_crd_test.go
- tests/eats/tasks_test.go
- tests/integration/clients_test.go
- tests/integration/events/events_test.go
- tests/integration/integration_suite_test.go
- tests/integration/opi/desire_app_test.go
- tests/integration/opi/list_app_test.go
- tests/integration/opi/task_completion_test.go
- tests/integration/opi/task_test.go
- tests/integration/task-reporter/task_reporter_test.go
see https://github.com/cloudfoundry/cf-for-k8s/issues/483#issue-711800977 for context about what all was broken by having a hardcoded UID. In short, containers that were built to run with non-2000 UIDs will not run. runAsNonRoot should prevent users from running as UID 0, giving them root on the host.
> stop hardcoding VCAP UID when desiring tasks and LRPs
